2002-03-23  Vladimir Makarov  <vmakarov@users.sourceforge.net>
	* Makefile.in: Check only_cocom_source_files on empty.

	* acconfig.h (socklen_t, HAVE_INET_ATON): New undefs.

	* configure.in: Check type scoklen_t, function inet_aton, and
	libaray -lxnet.

	* configure: Update.

	* AMMUNITION/cocom-config.h.in: Update.

	* DINO/Makefile.in (ipcerr_lib): New macro.
	(DINO_EXTERN_LIBS, DINO_EXTERN_LIBS_PATH, source): Add files for
	ipcerr.
	(ipcerr_lib): New rule for building.
	(install, uninstall, create-distdir, depend): Add files for
	ipcerr.
	Update dependencies.

	* DINO/compare.tst: Add test numbers.

	* DINO/d_main.c (get_library_search_function): Add code for ipcerr
	and socket.
	(ipcerr_address, socket_address): Add externals.

	* DINO/d_built.h (process_errno_call): New prototype.

	* DINO/d_func.c (process_system_errors): Use strerror for
	default message.
	(process_errno_call): New function.

	* DINO/d_ir.sprut (ENVIROMENT): New function __process_errno__.
	(PROCESS_ERRNO_NAME): New macro.
	(process_errno_decl): New global variable.
	(decls_table): Add entry for __process_errno__.

	* DINO/socket.d (ipcerr): Include it.
	(socket_error): Extend error.
	(invalid_address, host_not_found, no_address, no_recovery): New
	classes in socket_error.
	(socket_errors): New variable.
	(socket_excepts): remove it from __scoket_package.
	(_socket_invalid_address, _socket_host_not_found,
	_socket_no_address, _socket_no_recovery, _socket_try_again): New
	private external vars.
	(generate_socket_exception): Change it.  Remove parameter.

	* DINO/socket_int.c: Include d_config.h.
	(_socket_invalid_address, _socket_host_not_found,
	_socket_no_address, _socket_no_recovery, _socket_try_again): New
	global vars.
	(get_ip_address, _gethostinfo, _getservent, _sread, _swrite,
	_recvfrom, _sendto, _accept, _stream_client, _dgram_client,
	_stream_server, _dgram_server): Process errors.
	(_socket_init): Set up _socket_invalid_address,
	_socket_host_not_found, _socket_no_address, _socket_no_recovery,
	_socket_try_again.
	(socket_address): New function.

	* MSTA/Makefile.in: Update dependencies.

	* NONA/Makefile.in: Ditto.

	* OKA/Makefile.in: Ditto.

	* SHILKA/Makefile.in: Ditto.

	* SPRUT/Makefile.in: Ditto.

	* AMMUNITION/Makefile.in: Ditto.

	* DINO/ipcerr.d: New file.

	* DINO/ipcerr_int.c: New file.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1854,13 +1854,44 @@ EOF
 
 
 
+cat > conftest.$ac_ext <<EOF
+#line 1859 "configure"
+#include "confdefs.h"
+#include <sys/types.h>
+#include <sys/socket.h>
+int main() {
+socklen_t l;
+; return 0; }
+EOF
+if { (eval echo configure:1867: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+  rm -rf conftest*
+  socklen=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  socklen=no
+fi
+rm -f conftest*
+echo $ac_n "checking whether socklen_t was defined""... $ac_c" 1>&6
+echo "configure:1878: checking whether socklen_t was defined" >&5
+if test $socklen = no; then
+ echo "$ac_t""no" 1>&6
+ cat >> confdefs.h <<\EOF
+#define socklen_t size_t
+EOF
+
+else
+ echo "$ac_t""yes" 1>&6
+fi
+
 echo $ac_n "checking return type of signal handlers""... $ac_c" 1>&6
-echo "configure:1859: checking return type of signal handlers" >&5
+echo "configure:1890: checking return type of signal handlers" >&5
 if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1864 "configure"
+#line 1895 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1877,7 +1908,7 @@ int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:1881: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1912: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_type_signal=void
 else
@@ -1899,12 +1930,12 @@ for ac_func in strerror memcpy memset memcmp memmove vsprintf dlopen getgroups\
                strtol strtod setitimer sigaction sigemptyset
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1903: checking for $ac_func" >&5
+echo "configure:1934: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1908 "configure"
+#line 1939 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1927,7 +1958,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:1931: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:1962: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -2010,11 +2041,11 @@ case $system in
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 2014 "configure"
+#line 2045 "configure"
 #include "confdefs.h"
 int i;main(){exit(0);}
 EOF
-if { (eval echo configure:2018: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2049: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   gnu_ld=yes
 else
@@ -2029,6 +2060,8 @@ fi
           CFLAGS=$save
           if test x$gnu_ld != x; then
             SPECIAL_LINK_OPTION=-Wl,-E
+          else
+	    SPECIAL_LINK_OPTION=
           fi
 	  ;;
 	IRIX.5*)
@@ -2074,6 +2107,87 @@ fi
 	  no_shlib=yes
 	  ;;
 esac
+
+echo $ac_n "checking for inet_ntoa in -lxnet""... $ac_c" 1>&6
+echo "configure:2113: checking for inet_ntoa in -lxnet" >&5
+ac_lib_var=`echo xnet'_'inet_ntoa | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lxnet  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 2121 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char inet_ntoa();
+
+int main() {
+inet_ntoa()
+; return 0; }
+EOF
+if { (eval echo configure:2132: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+  xnet=yes
+else
+  echo "$ac_t""no" 1>&6
+xnet=not
+fi
+
+
+if test $xnet = yes; then
+   SPECIAL_LINK_OPTION="$SPECIAL_LINK_OPTION -lxnet"
+fi
+
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 2162 "configure"
+#include "confdefs.h"
+#include <sys/socket.h>
+#include <arpa/inet.h>
+#include <netinet/in.h>
+main () {struct in_addr i;inet_aton ("127.0.0.1", &i);return 0;}
+EOF
+if { (eval echo configure:2169: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  inet_aton=yes
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  inet_aton=no
+fi
+rm -fr conftest*
+fi
+
+echo $ac_n "checking whether inet_aton was defined""... $ac_c" 1>&6
+echo "configure:2182: checking whether inet_aton was defined" >&5
+if test $inet_aton = yes; then
+ echo "$ac_t""yes" 1>&6
+ cat >> confdefs.h <<\EOF
+#define HAVE_INET_ATON 1
+EOF
+
+else
+ echo "$ac_t""no" 1>&6
+fi
 
 DINO_LIB_SUFFIX=$LIB_SUFFIX
 EXTERN_LIB_SUFFIX=$LIB_SUFFIX
