2003-09-30  Vladimir Makarov  <vmakarov@users.sourceforge.net>
        * configure.in: Check size of char *.

	* configure: Update.

	* AMMUNITION/cocom-config.h.in: Add undef for SIZEOF_CHAR_P.

	* AMMUNITION/earley.c (make_parse):  Add state to the stack even
	if the situation position is zero.

	* AMMUNITION/{earley.tst.in, earley++.tst.in}: Add test for empty
	rule with anode.

	* DINO/d_blocktab.{ch}: Rename them into d_runtab.{ch}.
	(initiate_blocks_table): Rename it onto initiate_run_tables.
	(set_func_class_no): New function.
	(finish_blocks_table): rename it onto finish_run_tables.

	* DINO/Makefile.in: Rename blocktab on runtab.

	* DINO/dino.dsp: Rename blocktab on runtab.

	* DINO/d_common.h: Define SIZEOF_CHAR_P for WIN32.

	* DINO/d_extern.sprut (func): Change field func onto func_no.
	(class): Change field class onto class_no.

	* DINO/d_func.c: Add include d_runtab.h.
	(internal_inside_call, array_sort_compare_function, sort_call,
	place_file_instance, print_val, create_instance,
	process_func_class_call, init_syntax_token, tree_to_heap,
	int_earley_parse): Use field func_{class_}no instead of
	func{class}.

	* DINO/d_heap.c: Rename blocktab on runtab.
	(node_mode_2_type, destroy_instances, hash_val, eq_key):

	* DINO/d_ir.sprut: (func_or_class, external_func): New field no.

	* DINO/d_context.c: Rename blocktab on runtab.
	(second_block_passing): Set up func_class_no.

	* DINO/d_dino.c: Rename blocktab on runtab.
	(dino_start): Rename finish_blocks_table on finish_run_tables.
	(dino_finish): Rename initiate_blocks_table on
	initiate_run_tables.

	* DINO/d_eval.c: Rename blocktab on runtab.
	(execute_a_period_operation): Use field func_{class_}no instead of
	func{class}.
	(evaluate_code): Ditto.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1893,9 +1893,48 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+echo $ac_n "checking size of char *""... $ac_c" 1>&6
+echo "configure:1898: checking size of char *" >&5
+if eval "test \"`echo '$''{'ac_cv_sizeof_char_p'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 1906 "configure"
+#include "confdefs.h"
+#include <stdio.h>
+int main()
+{
+  FILE *f=fopen("conftestval", "w");
+  if (!f) return(1);
+  fprintf(f, "%d\n", sizeof(char *));
+  return(0);
+}
+EOF
+if { (eval echo configure:1917: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  ac_cv_sizeof_char_p=`cat conftestval`
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+  ac_cv_sizeof_char_p=0
+fi
+rm -fr conftest*
+fi
+
+fi
+echo "$ac_t""$ac_cv_sizeof_char_p" 1>&6
+cat >> confdefs.h <<EOF
+#define SIZEOF_CHAR_P $ac_cv_sizeof_char_p
+EOF
+
+
 
 cat > conftest.$ac_ext <<EOF
-#line 1899 "configure"
+#line 1938 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <sys/socket.h>
@@ -1903,7 +1942,7 @@ int main() {
 socklen_t l;
 ; return 0; }
 EOF
-if { (eval echo configure:1907: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1946: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   socklen=yes
 else
@@ -1914,7 +1953,7 @@ else
 fi
 rm -f conftest*
 echo $ac_n "checking whether socklen_t was defined""... $ac_c" 1>&6
-echo "configure:1918: checking whether socklen_t was defined" >&5
+echo "configure:1957: checking whether socklen_t was defined" >&5
 if test $socklen = no; then
  echo "$ac_t""no" 1>&6
  cat >> confdefs.h <<\EOF
@@ -1926,12 +1965,12 @@ else
 fi
 
 echo $ac_n "checking return type of signal handlers""... $ac_c" 1>&6
-echo "configure:1930: checking return type of signal handlers" >&5
+echo "configure:1969: checking return type of signal handlers" >&5
 if eval "test \"`echo '$''{'ac_cv_type_signal'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1935 "configure"
+#line 1974 "configure"
 #include "confdefs.h"
 #include <sys/types.h>
 #include <signal.h>
@@ -1948,7 +1987,7 @@ int main() {
 int i;
 ; return 0; }
 EOF
-if { (eval echo configure:1952: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:1991: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ac_cv_type_signal=void
 else
@@ -1970,12 +2009,12 @@ for ac_func in strerror memcpy memset memcmp memmove vsprintf dlopen getgroups\
                strtol strtod setitimer sigaction sigemptyset
 do
 echo $ac_n "checking for $ac_func""... $ac_c" 1>&6
-echo "configure:1974: checking for $ac_func" >&5
+echo "configure:2013: checking for $ac_func" >&5
 if eval "test \"`echo '$''{'ac_cv_func_$ac_func'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 1979 "configure"
+#line 2018 "configure"
 #include "confdefs.h"
 /* System header to define __stub macros and hopefully few prototypes,
     which can conflict with char $ac_func(); below.  */
@@ -1998,7 +2037,7 @@ $ac_func();
 
 ; return 0; }
 EOF
-if { (eval echo configure:2002: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2041: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_func_$ac_func=yes"
 else
@@ -2081,11 +2120,11 @@ case $system in
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 2085 "configure"
+#line 2124 "configure"
 #include "confdefs.h"
 int i;main(){exit(0);}
 EOF
-if { (eval echo configure:2089: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2128: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   gnu_ld=yes
 else
@@ -2160,11 +2199,11 @@ if test "$GCC" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 2164 "configure"
+#line 2203 "configure"
 #include "confdefs.h"
 int i;main(){exit(0);}
 EOF
-if { (eval echo configure:2168: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2207: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   inline_limit=yes
 else
@@ -2186,7 +2225,7 @@ fi
 fi
 
 echo $ac_n "checking for inet_ntoa in -lxnet""... $ac_c" 1>&6
-echo "configure:2190: checking for inet_ntoa in -lxnet" >&5
+echo "configure:2229: checking for inet_ntoa in -lxnet" >&5
 ac_lib_var=`echo xnet'_'inet_ntoa | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -2194,7 +2233,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lxnet  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 2198 "configure"
+#line 2237 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -2205,7 +2244,7 @@ int main() {
 inet_ntoa()
 ; return 0; }
 EOF
-if { (eval echo configure:2209: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:2248: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -2235,14 +2274,14 @@ if test "$cross_compiling" = yes; then
     { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
 else
   cat > conftest.$ac_ext <<EOF
-#line 2239 "configure"
+#line 2278 "configure"
 #include "confdefs.h"
 #include <sys/socket.h>
 #include <arpa/inet.h>
 #include <netinet/in.h>
 main () {struct in_addr i;inet_aton ("127.0.0.1", &i);return 0;}
 EOF
-if { (eval echo configure:2246: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+if { (eval echo configure:2285: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
 then
   inet_aton=yes
 else
@@ -2255,7 +2294,7 @@ rm -fr conftest*
 fi
 
 echo $ac_n "checking whether inet_aton was defined""... $ac_c" 1>&6
-echo "configure:2259: checking whether inet_aton was defined" >&5
+echo "configure:2298: checking whether inet_aton was defined" >&5
 if test $inet_aton = yes; then
  echo "$ac_t""yes" 1>&6
  cat >> confdefs.h <<\EOF
